version: '3'

services:
    api:
        container_name: m5_panda_zap_API
        build:
            context: .
            dockerfile: api.Dockerfile
        environment:
            M5_JWT_SECRET: secret
        ports:
            - "11005:11005"
        command: "go run main.go"
