version: '3.3'

services:
   db:
    container_name: a6db
    image: secdevlabs/a6-the-mistery:db-version-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

   wordpress:
    container_name: a6-wordpress
    depends_on:
      - db
    image: secdevlabs/a6-the-mistery:wp-version-2
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress